# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hometask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='no.gif', upload_to=''),
        ),
    ]
